[package]
name = "clex"
version = "0.2.0"
authors = ["lonelyhentai <master@evernightfireworks.com>"]
edition = "2018"

[dependencies]
regex_engine = { path = "../regex_engine", version="0.2.0" }
lazy_static = "1.3.0"
