[package]
name = "naive_compiler"
version = "0.1.1"
authors = ["lonelyhentai <master@evernightfireworks.com>"]
edition = "2018"

[dependencies]
regex_engine = { path =  './regex_engine'}
clex = { path = './clex' }
clap = "^2.32.0"
serde_json = "1.0.39"
