[package]
name = "complicated_libc"
version = "0.1.0"
authors = ["lonelyhentai <lonely_hentai@hotmail.com>"]
edition = "2018"

[dependencies]
libc = "^0.2"

[lib]
name = "rust_log"
crate-type = ["cdylib"]
