[package]
name = "naive_compiler"
version = "0.2.0"
authors = ["lonelyhentai <master@evernightfireworks.com>"]
edition = "2018"

[dependencies]
clex = { path = './clex', version="0.1.1" }
cparser = { path="./cparser", version="0.0.1" }
clap = "^2.32.0"
serde_json = "1.0.39"
