[package]
name = "dive_into_rust"
version = "0.1.0"
authors = ["lonelyhentai <master@evernightfireworks.com>"]
edition = "2018"

[dependencies]
hello_macro = { path = "./hello_macro" }
hello_macro_derive = { path = "./hello_macro_derive" }
scoped_threadpool = "^0.1.9"
dirs = "^1.0.4"
