[package]
name = "yalc"
version = "0.0.1"
authors = ["lonelyhentai <master@evernightfireworks>"]

[dependencies]
regex = "1.0"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
llvm-sys = "*"
llvm-sys-wrapper="*"

[dev-dependencies]
serde_json = "1.0"
