[package]
name = "actix_learn"
version = "0.0.1"
authors = ["lonelyhentai <master@evernightfireworks.com>"]
edition = "2018"

[lib]
name = "actix_learn"
path = "src/lib.rs"

[dependencies]
actix = "0.7"
actix-web = "0.7"
futures = "0.1.27"